#!/usr/bin/env bash
#
# bootstrap-local-stellar.sh
#
# Bootstraps a local Stellar network for the devcontainer quickstart:
#   1. Waits for the local Stellar RPC / Horizon / Friendbot endpoints to be ready.
#   2. Fetches the test attestation contract WASM from the contracts repo release.
#   3. Deploys the contract to the local network using the Stellar CLI.
#   4. Writes the resulting contract id and network config to .env.local.
#
# This script is intended to run inside the devcontainer after the
# `stellar/quickstart --local --enable rpc` compose service is up.
#
# Usage:
#   scripts/bootstrap-local-stellar.sh
#
# Environment overrides:
#   STELLAR_RPC_URL        (default: http://localhost:8000/soroban/rpc)
#   STELLAR_HORIZON_URL    (default: http://localhost:8000)
#   STELLAR_FRIENDBOT_URL  (default: http://localhost:8000/friendbot)
#   STELLAR_NETWORK        (default: local)
#   STELLAR_NETWORK_PASSPHRASE (default: "Standalone Network ; February 2017")
#   CONTRACTS_REPO         (default: the attestation contracts repo)
#   CONTRACTS_RELEASE_TAG  (default: latest)
#   CONTRACT_WASM_NAME     (default: attestation.wasm)
#   ENV_FILE               (default: .env.local)
#   STELLAR_IDENTITY       (default: local-dev)

set -euo pipefail

STELLAR_RPC_URL="${STELLAR_RPC_URL:-http://localhost:8000/soroban/rpc}"
STELLAR_HORIZON_URL="${STELLAR_HORIZON_URL:-http://localhost:8000}"
STELLAR_FRIENDBOT_URL="${STELLAR_FRIENDBOT_URL:-http://localhost:8000/friendbot}"
STELLAR_NETWORK="${STELLAR_NETWORK:-local}"
STELLAR_NETWORK_PASSPHRASE="${STELLAR_NETWORK_PASSPHRASE:-Standalone Network ; February 2017}"
CONTRACTS_REPO="${CONTRACTS_REPO:-stellar/attestation-contracts}"
CONTRACTS_RELEASE_TAG="${CONTRACTS_RELEASE_TAG:-latest}"
CONTRACT_WASM_NAME="${CONTRACT_WASM_NAME:-attestation.wasm}"
ENV_FILE="${ENV_FILE:-.env.local}"
STELLAR_IDENTITY="${STELLAR_IDENTITY:-local-dev}"

log() { printf '[bootstrap-local-stellar] %s\n' "$*" >&2; }

require() {
  if ! command -v "$1" >/dev/null 2>&1; then
    log "error: required command '$1' not found in PATH"
    exit 1
  fi
}

wait_for() {
  local url="$1" name="$2" attempts="${3:-60}"
  log "waiting for ${name} at ${url} ..."
  for _ in $(seq 1 "$attempts"); do
    if curl -fsS -o /dev/null "$url"; then
      log "${name} is ready"
      return 0
    fi
    sleep 2
  done
  log "error: timed out waiting for ${name} at ${url}"
  return 1
}

require curl
require stellar

# 1. Wait for the local Stellar stack to accept requests.
wait_for "${STELLAR_HORIZON_URL}/health" "Horizon"
wait_for "${STELLAR_RPC_URL}" "Stellar RPC"

# 2. Fetch the contract WASM from the contracts repo release.
WASM_DIR="$(mktemp -d)"
trap 'rm -rf "${WASM_DIR}"' EXIT
WASM_PATH="${WASM_DIR}/${CONTRACT_WASM_NAME}"

if [[ "${CONTRACTS_RELEASE_TAG}" == "latest" ]]; then
  WASM_URL="https://github.com/${CONTRACTS_REPO}/releases/latest/download/${CONTRACT_WASM_NAME}"
else
  WASM_URL="https://github.com/${CONTRACTS_REPO}/releases/download/${CONTRACTS_RELEASE_TAG}/${CONTRACT_WASM_NAME}"
fi

log "fetching contract WASM from ${WASM_URL}"
if ! curl -fsSL -o "${WASM_PATH}" "${WASM_URL}"; then
  log "error: failed to download contract WASM from ${WASM_URL}"
  exit 1
fi

# 3. Ensure a funded local identity exists, then deploy the contract.
if ! stellar keys address "${STELLAR_IDENTITY}" >/dev/null 2>&1; then
  log "creating and funding local identity '${STELLAR_IDENTITY}'"
  stellar keys generate "${STELLAR_IDENTITY}" --network "${STELLAR_NETWORK}" --fund
fi

DEPLOYER_ADDRESS="$(stellar keys address "${STELLAR_IDENTITY}")"
log "deploying contract as ${DEPLOYER_ADDRESS}"

CONTRACT_ID="$(stellar contract deploy \
  --wasm "${WASM_PATH}" \
  --source "${STELLAR_IDENTITY}" \
  --network "${STELLAR_NETWORK}" \
  --rpc-url "${STELLAR_RPC_URL}" \
  --network-passphrase "${STELLAR_NETWORK_PASSPHRASE}")"

if [[ -z "${CONTRACT_ID}" ]]; then
  log "error: contract deployment did not return a contract id"
  exit 1
fi

log "deployed attestation contract: ${CONTRACT_ID}"

# 4. Write the local environment file consumed by the app.
log "writing ${ENV_FILE}"
cat > "${ENV_FILE}" <<EOF
# Generated by scripts/bootstrap-local-stellar.sh — do not commit.
STELLAR_NETWORK=${STELLAR_NETWORK}
STELLAR_NETWORK_PASSPHRASE=${STELLAR_NETWORK_PASSPHRASE}
STELLAR_RPC_URL=${STELLAR_RPC_URL}
STELLAR_HORIZON_URL=${STELLAR_HORIZON_URL}
STELLAR_FRIENDBOT_URL=${STELLAR_FRIENDBOT_URL}
STELLAR_ATTESTATION_CONTRACT_ID=${CONTRACT_ID}
EOF

log "done. Local Stellar network is ready for live-mode attestation flows."
