-- Idempotency keys for destructive Server Actions (issue #626).
--
-- Network retries on slow connections can double-submit actions such as
-- regenerateCardId and createEmergencyCapability.  Each form render generates
-- a UUID hidden input; the action wrapper inserts-or-fetches on that key and
-- replays the stored result on duplicates.
--
-- Schema:
--   user_id     — scoped per user so keys from different users never collide.
--   key         — UUID generated by the client form (hidden input).
--   action      — discriminator matching the Server Action function name.
--   request_hash — SHA-256 of the canonical request payload; a duplicate
--                  with a DIFFERENT hash is rejected (guard against payload
--                  mutation under the same key).
--   response    — the serialized action result, replayed on duplicates.
--   created_at  — purge rows older than 24 h.

create table public.idempotency_keys (
  id            uuid        primary key default gen_random_uuid(),
  user_id       uuid        not null references auth.users(id) on delete cascade,
  key           uuid        not null,
  action        text        not null,
  request_hash  text        not null check (request_hash ~ '^[0-9a-f]{64}$'),
  response      jsonb       not null default '{}',
  created_at    timestamptz not null default now(),
  constraint idempotency_keys_user_key unique (user_id, key)
);

comment on table public.idempotency_keys is
  'Per-user, per-form-render idempotency tokens for destructive Server Actions '
  '(issue #626).  Rows are automatically purged after 24 h.';

comment on column public.idempotency_keys.request_hash is
  'SHA-256 of the canonical request payload.  A duplicate key with a '
  'different hash is rejected to guard against accidental payload mutation.';

comment on column public.idempotency_keys.response is
  'Serialized action result.  PHI and capability tokens must NEVER appear here; '
  'use status codes and opaque IDs only.';

create index idempotency_keys_user_created_idx
  on public.idempotency_keys(user_id, created_at desc);

-- ── RLS ────────────────────────────────────────────────────────────────────

alter table public.idempotency_keys enable row level security;

-- The application reads/writes via the service-role client inside Server
-- Actions (so auth.uid() is available via the normal Supabase server client
-- but the idempotency wrapper uses an admin client for the atomic upsert).
grant select, insert, update on public.idempotency_keys to service_role;
grant select on public.idempotency_keys to authenticated;

create policy idempotency_keys_select_own on public.idempotency_keys
  for select to authenticated using (auth.uid() = user_id);

-- ── Atomic insert-or-fetch RPC ─────────────────────────────────────────────

create or replace function public.insert_or_fetch_idempotency_key(
  p_user_id      uuid,
  p_key          uuid,
  p_action       text,
  p_request_hash text,
  p_response     jsonb default null
)
returns jsonb
language plpgsql security definer set search_path = '' as $$
declare
  v_row public.idempotency_keys;
begin
  -- Try to claim an existing row first (no write contention on duplicate path).
  select * into v_row
    from public.idempotency_keys
   where user_id = p_user_id and key = p_key;

  if found then
    -- Duplicate key: verify the request payload hash matches.
    if v_row.request_hash <> p_request_hash then
      raise exception using
        errcode = '23514',
        message = 'IDEMPOTENCY_HASH_MISMATCH',
        detail  = 'The same idempotency key was submitted with a different payload.';
    end if;
    -- Return the stored response for replay.
    return jsonb_build_object(
      'duplicate',  true,
      'response',   v_row.response
    );
  end if;

  -- First occurrence — insert and return the provided (or null) response.
  insert into public.idempotency_keys(user_id, key, action, request_hash, response)
  values (p_user_id, p_key, p_action, p_request_hash, coalesce(p_response, '{}'))
  on conflict (user_id, key) do update
    -- Another concurrent request won the race; return its row.
    set key = excluded.key
  returning * into v_row;

  if v_row.request_hash <> p_request_hash then
    raise exception using
      errcode = '23514',
      message = 'IDEMPOTENCY_HASH_MISMATCH',
      detail  = 'Concurrent request stored a different payload hash.';
  end if;

  return jsonb_build_object('duplicate', false, 'response', v_row.response);
end;
$$;

revoke all on function public.insert_or_fetch_idempotency_key(uuid,uuid,text,text,jsonb) from public;
grant execute on function public.insert_or_fetch_idempotency_key(uuid,uuid,text,text,jsonb) to service_role;

-- ── 24-hour purge function (call from a cron job or the dispatch endpoint) ──

create or replace function public.purge_expired_idempotency_keys()
returns integer
language sql security definer set search_path = '' as $$
  with deleted as (
    delete from public.idempotency_keys
     where created_at < now() - interval '24 hours'
    returning id
  )
  select count(*)::integer from deleted;
$$;

revoke all on function public.purge_expired_idempotency_keys() from public;
grant execute on function public.purge_expired_idempotency_keys() to service_role;
