import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { after } from "next/server";

import { logError } from "@/lib/logging/logger";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { EmergencyCardContent } from "./card-content";

/**
 * ROUTE: /card/[id]
 *
 * OVERVIEW:
 * This is the patient's permanent, stable public emergency card link. It is
 * generated and owned by the patient directly, not through a capability-share
 * flow. The link itself (the card ID/UUID) acts as a bearer capability — anyone
 * with the link can view the card — but it is permanent and directly under the
 * patient's control (they can regenerate it or manage who receives it).
 *
 * KEY DIFFERENCES FROM /card/c/[token]:
 * - Link type: Permanent patient-controlled link (UUID)
 * - Generated by: Patient directly (stored in their profile)
 * - Expiry: None — remains valid indefinitely until patient revokes/regenerates
 * - Scope: No built-in time or view-count limits (policy set by patient ownership)
 * - Revocation: Patient can regenerate their card ID to invalidate all old links
 * - Authorization kind: "legacy" (historical bearer-token-like sharing)
 * - Access logging: Recorded against the card ID itself, not a capability
 *
 * VERSUS /card/c/[token] (Capability-Share Link):
 * - Link type: Time-limited, scoped, revocable capability token
 * - Generated by: Capability-share flow (patient grants to specific person/time)
 * - Expiry: Configurable by patient (can be hours, days, etc.)
 * - Scope: Can include view-count limits, access times, or other constraints
 * - Revocation: Independently revocable without affecting patient's main card
 * - Authorization kind: "capability" (explicit grant with policy)
 * - Access logging: Recorded against the capability, enabling audit trails per grant
 *
 * SECURITY PROPERTIES:
 * - The card ID acts as a secret (not indexed, never crawled, kept out of logs)
 * - This route assumes the bearer has legitimate access (no additional auth required)
 * - Offline-capable: The responder's device can use a service worker to view
 *   this card without connectivity, from the structured envelope
 *
 * Every live access is authorized/accounted for asynchronously. Offline use
 * is served exclusively from the structured service-worker envelope, never a
 * stale ISR document that could outlive a revocation or revision update.
 */
export const dynamic = "force-dynamic";

// This page is unauthenticated and reachable by anyone with the link (that's
// the point — a responder scanning a QR shouldn't need to log in), but it
// must never be indexed or crawled.
export const metadata: Metadata = {
  title: "Emergency Card · Lafiya",
  robots: { index: false, follow: false },
};

const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export default async function PublicCardPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;

  if (!UUID_PATTERN.test(id)) {
    notFound();
  }

  const supabase = await createClient();
  const { data, error } = await supabase.rpc("get_emergency_card", {
    p_card_id: id,
  });

  if (error) {
    // Public card IDs are bearer-like capabilities: keep them out of logs,
    // traces, and error-reporting payloads.
    logError("Failed to load emergency card", new Error("CARD_LOOKUP_FAILED"), {
      route: "/card/[id]",
    });
    throw new Error("UNAVAILABLE");
  }

  if (!data || data.length === 0) {
    notFound();
  }

  after(async () => {
    try {
      await createAdminClient().rpc("record_legacy_card_access_event", {
        p_card_id: id,
      });
    } catch (accessEventError) {
      logError("Failed to record emergency-card access", accessEventError, {
        route: "/card/[id]",
      });
    }
  });

  return <EmergencyCardContent card={data[0]} authorizationKind="legacy" />;
}
