import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { after } from "next/server";

import {
  digestCapability,
  isCapabilityToken,
} from "@/lib/emergency/capability";
import { logError } from "@/lib/logging/logger";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";

import { EmergencyCardContent } from "../../[id]/card-content";

/**
 * ROUTE: /card/c/[token]
 *
 * OVERVIEW:
 * This is a time-limited, scoped, and revocable capability-share link. It is
 * generated through the capability-share flow when the patient explicitly grants
 * temporary access to a specific person or responder. The token carries a policy
 * that defines expiry, view limits, and other constraints, and it can be revoked
 * independently without affecting the patient's primary card link.
 *
 * KEY DIFFERENCES FROM /card/[id]:
 * - Link type: Time-limited, scoped capability token (base64url-encoded random bytes)
 * - Generated by: Capability-share flow (patient grants to specific person/time)
 * - Expiry: Configurable by patient at grant time (e.g., valid for 48 hours)
 * - Scope: May include view-count budgets, time windows, or other constraints
 * - Revocation: Independently revocable; patient can revoke one grant without affecting others
 * - Authorization kind: "capability" (explicit, auditable grant)
 * - Access logging: Recorded against the capability ID for fine-grained audit trails
 *
 * VERSUS /card/[id] (Permanent Patient Card):
 * - Link type: Permanent patient-controlled UUID link
 * - Generated by: Patient directly (stored in profile)
 * - Expiry: None — valid indefinitely until patient regenerates their card
 * - Scope: No built-in limits (bearer-like sharing under patient control)
 * - Revocation: Requires regenerating the entire card ID (affects all old links)
 * - Authorization kind: "legacy" (historical bearer pattern)
 * - Access logging: Recorded against the card ID, not a grant
 *
 * SECURITY PROPERTIES:
 * - The token is a one-time capability: only the digest is persisted in the DB
 * - Every access checks the capability's policy (expiry, revocation status, view budget)
 * - Policies are checked for every live navigation (never cached by CDN or ISR)
 * - The public route does not distinguish between expired, revoked, exhausted, or
 *   malformed tokens — all result in 404 — to prevent the route from becoming an oracle
 *
 * A capability's policy (expiry, revocation, and view budget) must be checked
 * for every live navigation. It is intentionally never ISR/CDN cached.
 */
export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  robots: { index: false, follow: false },
};

export default async function CapabilityCardPage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  if (!isCapabilityToken(token)) notFound();

  const supabase = await createClient();
  const { data, error } = await supabase.rpc("consume_emergency_capability", {
    p_token_digest: digestCapability(token),
  });

  if (error) {
    logError(
      "Failed to resolve emergency capability",
      new Error("CAPABILITY_LOOKUP_FAILED"),
      {
        route: "/card/c/[token]",
      },
    );
    throw new Error("UNAVAILABLE");
  }

  const resolution = data?.[0];
  if (
    !resolution ||
    resolution.access_state !== "active" ||
    !resolution.capability_id
  ) {
    // Do not distinguish malformed, unknown, revoked, exhausted, or expired
    // capability values. That prevents the public route becoming an oracle.
    notFound();
  }

  const { capability_id: capabilityId, ...card } = resolution;
  after(async () => {
    try {
      const admin = createAdminClient();
      await admin.rpc("record_card_access_event", {
        p_capability_id: capabilityId,
        p_access_kind: "capability",
        p_outcome: "served",
      });
    } catch (accessEventError) {
      // Deferred accountability is best-effort by design. No raw capability,
      // identifier, patient data, or error payload reaches the logger.
      logError("Failed to record emergency-card access", accessEventError, {
        route: "/card/c/[token]",
      });
    }
  });

  return <EmergencyCardContent card={card} authorizationKind="capability" />;
}
